# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.19.4
yarn_mappings=1.19.4+build.2
loader_version=0.15.10
fabric_kotlin_version=1.10.19+kotlin.1.9.23
# Mod Properties
mod_version=0.3.0.a2
compatible_mc_version=1.20.1
detailed_mc_version=>=1.20.1
maven_group=name.nkid00
archives_name=redstone-computer-utilities
# Dependencies
fabric_version=0.87.2+1.19.4
gson_version=2.10
guava_version=31.1-jre
netty_version=4.1.82.Final
