name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: build
        run: ./gradlew build
      - name: find artifact
        run: echo "artifact=$( find ./build/libs/ -name *.jar -not -name *-dev.jar -not -name *-sources.jar )" >> $GITHUB_ENV
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.artifact }}
      - name: release artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: ${{ env.artifact }}
